
# Serve Homepage at root "/"
location = / { return 301 /; }

location / {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream http://homepage:3000;
    proxy_pass $upstream;
    proxy_redirect off;
}
