server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.__BASE_DOMAIN__;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    
    # enable subfolder method reverse proxy confs
    include /config/nginx/active-confs/*.subfolder.conf;

    location / {
        # Hardening step 1 
        # Generate the file with : docker exec -it swag htpasswd -c /config/nginx/.htpasswd yourusername
        # Then uncomment the line below to enable basic auth on the admin subdomain. 
        # include /config/nginx/custom/admin-auth.conf;

        # Hardening step 2 (see docs for more information)
        # Please follow the instructions in the documentation to set up OIDC authentication with Keycloak and then uncomment the line 
        # below to enable it.
        # Note : once the sandbox is working, you can set up OIDC auth and then disable basic auth by commenting out the include line 
        # for admin-auth.conf and uncommenting the line for admin-auth-oidc.conf. You can also keep both enabled if you want to have both options available.
        # include /config/nginx/custom/admin-auth-oidc.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app homer;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

}