# swag/config/nginx/client-stacks/__STACK__.conf
# Generated by: make stack-add STACK=__STACK__ PORT=__PORT__ MODE=subfolder
#
# Exposes __STACK__ at https://labs.__BASE_DOMAIN__/__STACK__/
# Auto-included by labs.__BASE_DOMAIN__ via:
#   include /config/nginx/client-stacks/*.conf;
#
# Checklist before activating:
#   [ ] Container __STACK__ joined network revproxy_apps
#   [ ] `make stack-check STACK=__STACK__` returns no errors
#   [ ] SWAG reloaded: docker compose exec swag nginx -s reload

location = /__STACK__ {
    return 301 /__STACK__/;
}

location ^~ /__STACK__/ {
    # ── Hardening step 2 — OIDC ──────────────────────────────────────────
    # Validate OIDC on the canary first, then uncomment the line below.
    # See docs/adding-a-downstream-stack.md § Security integration.
    #
    # include /config/nginx/custom/admin-auth-oidc.conf;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    set $upstream_app __STACK__;
    set $upstream_port __PORT__;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
}
