# swag/config/nginx/site-confs/__STACK__.subdomain.conf
# Generated by: make stack-add STACK=__STACK__ PORT=__PORT__ MODE=subdomain
#
# Exposes __STACK__ at https://__STACK__.__BASE_DOMAIN__
#
# Checklist before activating:
#   [ ] DNS A record: __STACK__.__BASE_DOMAIN__ → server IP
#   [ ] Container __STACK__ joined network revproxy_apps
#   [ ] `make stack-check STACK=__STACK__` returns no errors
#   [ ] SWAG reloaded: docker compose exec swag nginx -s reload

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name __STACK__.__BASE_DOMAIN__;

    include /config/nginx/ssl.conf;

    # ── Hardening step 2 — OIDC ────────────────────────────────────────────
    # Validate OIDC on the canary first, then uncomment the block below.
    # See docs/adding-a-downstream-stack.md § Security integration.
    #
    #location @oauth2_start {
    #    return 302 /oauth2/start?rd=$scheme://$host$request_uri;
    #}

    location / {
        # Hardening step 2 — uncomment to enable OIDC:
        # include /config/nginx/custom/admin-auth-oidc.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app __STACK__;
        set $upstream_port __PORT__;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
