# grafana/prometheus/targets/downstream/__STACK__.yml
# Generated by: make stack-add STACK=__STACK__ PORT=__PORT__
#
# Prometheus scrape target for downstream stack: __STACK__
# Auto-discovered via file_sd_configs (refresh: 60s — no restart needed).
#
# Action required: set the correct metrics port below (__METRICS_PORT__).
# If this stack has no /metrics endpoint, delete this file.

- targets:
    - __STACK__:__METRICS_PORT__
  labels:
    job: __STACK__
    stack: __STACK__
    service: __STACK__
    domain: labs
    env: prod
